### ISSUE TITLE
Dark mode is broken in win11?

### ISSUE THREAD

**Issue by SrGeneroso** [probablykasper/remind-me-again#1]
I can't see the text as I'm writing, may be dark mode or even win11. Let me know if I can send you system data to help you.

<img width="302" alt="Lni6OEMDte" src="https://user-images.githubusercontent.com/5541794/179692321-f527d479-a61e-4112-afe4-60aaa6a6c35e.png">

**Comment by kasper9n** [comment]
Will look into it, the same thing probably happens on all of Windows and Linux

**Comment by kasper9n** [comment]
Should be fixed in [v1.0.1](https://github.com/probablykasper/remind-me-again/releases/tag/v1.0.1)
